# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vue1_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_state(object):
    def setupUi(self, Login_state):
        Login_state.setObjectName("Login_state")
        Login_state.resize(629, 526)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(Login_state.sizePolicy().hasHeightForWidth())
        Login_state.setSizePolicy(sizePolicy)
        Login_state.setStyleSheet("QWidget#Login_state{\n"
"background-image:url(C:/Users/Christian/Desktop/素材/logo);\n"
"background-repeat:no-repeat;\n"
"back\n"
"}")
        self.label = QtWidgets.QLabel(Login_state)
        self.label.setGeometry(QtCore.QRect(170, 210, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login_state)
        self.label_2.setGeometry(QtCore.QRect(170, 300, 71, 31))
        self.label_2.setObjectName("label_2")
        self.account = QtWidgets.QLineEdit(Login_state)
        self.account.setGeometry(QtCore.QRect(240, 210, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.account.sizePolicy().hasHeightForWidth())
        self.account.setSizePolicy(sizePolicy)
        self.account.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.account.setStyleSheet("border: 2px solid grey")
        self.account.setObjectName("account")
        self.pwdtxt = QtWidgets.QLineEdit(Login_state)
        self.pwdtxt.setGeometry(QtCore.QRect(240, 300, 201, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pwdtxt.sizePolicy().hasHeightForWidth())
        self.pwdtxt.setSizePolicy(sizePolicy)
        self.pwdtxt.setAutoFillBackground(False)
        self.pwdtxt.setStyleSheet("border: 2px solid grey")
        self.pwdtxt.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pwdtxt.setObjectName("pwdtxt")
        self.login = QtWidgets.QPushButton(Login_state)
        self.login.setGeometry(QtCore.QRect(280, 390, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setStyleSheet("")
        self.login.setObjectName("login")
        self.label_3 = QtWidgets.QLabel(Login_state)
        self.label_3.setGeometry(QtCore.QRect(150, 110, 361, 31))
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Login_state)
        QtCore.QMetaObject.connectSlotsByName(Login_state)

    def retranslateUi(self, Login_state):
        _translate = QtCore.QCoreApplication.translate
        Login_state.setWindowTitle(_translate("Login_state", "Form"))
        self.label.setText(_translate("Login_state", "<html><head/><body><p><span style=\" color:#008b95;\">账号：</span></p></body></html>"))
        self.label_2.setText(_translate("Login_state", "<html><head/><body><p><span style=\" color:#008b95;\">密码：</span></p></body></html>"))
        self.login.setText(_translate("Login_state", "确认"))
        self.label_3.setText(_translate("Login_state", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#008b95;\">安规测试仪使用</span></p></body></html>"))
