# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testingpage.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1382, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.testing_data = QtWidgets.QTableWidget(self.groupBox_4)
        self.testing_data.setAutoScroll(False)
        self.testing_data.setRowCount(10)
        self.testing_data.setColumnCount(9)
        self.testing_data.setObjectName("testing_data")
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.testing_data.setHorizontalHeaderItem(8, item)
        self.testing_data.horizontalHeader().setDefaultSectionSize(127)
        self.testing_data.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.testing_data)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("groupbox{\n"
"    background color: #7\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Product_No = QtWidgets.QLineEdit(self.groupBox)
        self.Product_No.setReadOnly(True)
        self.Product_No.setObjectName("Product_No")
        self.gridLayout.addWidget(self.Product_No, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.OrderID = QtWidgets.QLineEdit(self.groupBox)
        self.OrderID.setReadOnly(True)
        self.OrderID.setObjectName("OrderID")
        self.gridLayout.addWidget(self.OrderID, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.testedNum = QtWidgets.QLineEdit(self.groupBox)
        self.testedNum.setReadOnly(True)
        self.testedNum.setObjectName("testedNum")
        self.gridLayout.addWidget(self.testedNum, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 6, 1, 1)
        self.testUsedTime = QtWidgets.QLineEdit(self.groupBox)
        self.testUsedTime.setReadOnly(True)
        self.testUsedTime.setObjectName("testUsedTime")
        self.gridLayout.addWidget(self.testUsedTime, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.Product_Type = QtWidgets.QLineEdit(self.groupBox)
        self.Product_Type.setReadOnly(True)
        self.Product_Type.setObjectName("Product_Type")
        self.gridLayout.addWidget(self.Product_Type, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.OrderNum = QtWidgets.QLineEdit(self.groupBox)
        self.OrderNum.setReadOnly(True)
        self.OrderNum.setObjectName("OrderNum")
        self.gridLayout.addWidget(self.OrderNum, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1)
        self.passedNum = QtWidgets.QLineEdit(self.groupBox)
        self.passedNum.setReadOnly(True)
        self.passedNum.setObjectName("passedNum")
        self.gridLayout.addWidget(self.passedNum, 1, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 6, 1, 1)
        self.IDnum = QtWidgets.QLineEdit(self.groupBox)
        self.IDnum.setReadOnly(True)
        self.IDnum.setObjectName("IDnum")
        self.gridLayout.addWidget(self.IDnum, 1, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.SAP_Num = QtWidgets.QLineEdit(self.groupBox)
        self.SAP_Num.setReadOnly(True)
        self.SAP_Num.setObjectName("SAP_Num")
        self.gridLayout.addWidget(self.SAP_Num, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.User_name = QtWidgets.QLineEdit(self.groupBox)
        self.User_name.setReadOnly(True)
        self.User_name.setObjectName("User_name")
        self.gridLayout.addWidget(self.User_name, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 4, 1, 1)
        self.failedNum = QtWidgets.QLineEdit(self.groupBox)
        self.failedNum.setReadOnly(True)
        self.failedNum.setObjectName("failedNum")
        self.gridLayout.addWidget(self.failedNum, 2, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 6, 1, 1)
        self.timeBox = QtWidgets.QLineEdit(self.groupBox)
        self.timeBox.setReadOnly(True)
        self.timeBox.setObjectName("timeBox")
        self.gridLayout.addWidget(self.timeBox, 2, 7, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusbox1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox1.setReadOnly(True)
        self.statusbox1.setObjectName("statusbox1")
        self.horizontalLayout_3.addWidget(self.statusbox1)
        self.statusbox2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox2.setReadOnly(True)
        self.statusbox2.setObjectName("statusbox2")
        self.horizontalLayout_3.addWidget(self.statusbox2)
        self.statusbox3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox3.setReadOnly(True)
        self.statusbox3.setObjectName("statusbox3")
        self.horizontalLayout_3.addWidget(self.statusbox3)
        self.statusbox4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox4.setReadOnly(True)
        self.statusbox4.setObjectName("statusbox4")
        self.horizontalLayout_3.addWidget(self.statusbox4)
        self.statusbox5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox5.setReadOnly(True)
        self.statusbox5.setObjectName("statusbox5")
        self.horizontalLayout_3.addWidget(self.statusbox5)
        self.statusbox6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox6.setReadOnly(True)
        self.statusbox6.setObjectName("statusbox6")
        self.horizontalLayout_3.addWidget(self.statusbox6)
        self.statusbox7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox7.setReadOnly(True)
        self.statusbox7.setObjectName("statusbox7")
        self.horizontalLayout_3.addWidget(self.statusbox7)
        self.statusbox8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox8.setReadOnly(True)
        self.statusbox8.setObjectName("statusbox8")
        self.horizontalLayout_3.addWidget(self.statusbox8)
        self.statusbox9 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox9.setReadOnly(True)
        self.statusbox9.setObjectName("statusbox9")
        self.horizontalLayout_3.addWidget(self.statusbox9)
        self.statusbox10 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox10.setReadOnly(True)
        self.statusbox10.setObjectName("statusbox10")
        self.horizontalLayout_3.addWidget(self.statusbox10)
        self.statusbox11 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox11.setReadOnly(True)
        self.statusbox11.setObjectName("statusbox11")
        self.horizontalLayout_3.addWidget(self.statusbox11)
        self.statusbox12 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox12.setReadOnly(True)
        self.statusbox12.setObjectName("statusbox12")
        self.horizontalLayout_3.addWidget(self.statusbox12)
        self.statusbox13 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox13.setReadOnly(True)
        self.statusbox13.setObjectName("statusbox13")
        self.horizontalLayout_3.addWidget(self.statusbox13)
        self.statusbox14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox14.setReadOnly(True)
        self.statusbox14.setObjectName("statusbox14")
        self.horizontalLayout_3.addWidget(self.statusbox14)
        self.statusbox15 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox15.setReadOnly(True)
        self.statusbox15.setObjectName("statusbox15")
        self.horizontalLayout_3.addWidget(self.statusbox15)
        self.statusbox16 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox16.setReadOnly(True)
        self.statusbox16.setObjectName("statusbox16")
        self.horizontalLayout_3.addWidget(self.statusbox16)
        self.statusbox17 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox17.setReadOnly(True)
        self.statusbox17.setObjectName("statusbox17")
        self.horizontalLayout_3.addWidget(self.statusbox17)
        self.statusbox18 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox18.setReadOnly(True)
        self.statusbox18.setObjectName("statusbox18")
        self.horizontalLayout_3.addWidget(self.statusbox18)
        self.statusbox19 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox19.setReadOnly(True)
        self.statusbox19.setObjectName("statusbox19")
        self.horizontalLayout_3.addWidget(self.statusbox19)
        self.statusbox20 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox20.setReadOnly(True)
        self.statusbox20.setObjectName("statusbox20")
        self.horizontalLayout_3.addWidget(self.statusbox20)
        self.statusbox21 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox21.setReadOnly(True)
        self.statusbox21.setObjectName("statusbox21")
        self.horizontalLayout_3.addWidget(self.statusbox21)
        self.statusbox22 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox22.setReadOnly(True)
        self.statusbox22.setObjectName("statusbox22")
        self.horizontalLayout_3.addWidget(self.statusbox22)
        self.statusbox23 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox23.setReadOnly(True)
        self.statusbox23.setObjectName("statusbox23")
        self.horizontalLayout_3.addWidget(self.statusbox23)
        self.statusbox24 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox24.setReadOnly(True)
        self.statusbox24.setObjectName("statusbox24")
        self.horizontalLayout_3.addWidget(self.statusbox24)
        self.statusbox25 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox25.setReadOnly(True)
        self.statusbox25.setObjectName("statusbox25")
        self.horizontalLayout_3.addWidget(self.statusbox25)
        self.statusbox26 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox26.setReadOnly(True)
        self.statusbox26.setObjectName("statusbox26")
        self.horizontalLayout_3.addWidget(self.statusbox26)
        self.statusbox27 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox27.setReadOnly(True)
        self.statusbox27.setObjectName("statusbox27")
        self.horizontalLayout_3.addWidget(self.statusbox27)
        self.statusbox28 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox28.setReadOnly(True)
        self.statusbox28.setObjectName("statusbox28")
        self.horizontalLayout_3.addWidget(self.statusbox28)
        self.statusbox29 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox29.setReadOnly(True)
        self.statusbox29.setObjectName("statusbox29")
        self.horizontalLayout_3.addWidget(self.statusbox29)
        self.statusbox30 = QtWidgets.QLineEdit(self.groupBox_5)
        self.statusbox30.setReadOnly(True)
        self.statusbox30.setObjectName("statusbox30")
        self.horizontalLayout_3.addWidget(self.statusbox30)
        self.gridLayout_4.addWidget(self.groupBox_5, 6, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.test_hints = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.test_hints.setFont(font)
        self.test_hints.setReadOnly(True)
        self.test_hints.setObjectName("test_hints")
        self.gridLayout_2.addWidget(self.test_hints, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 5, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.startBtn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_3.addWidget(self.startBtn, 0, 0, 1, 1)
        self.resetBtn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.resetBtn.setFont(font)
        self.resetBtn.setObjectName("resetBtn")
        self.gridLayout_3.addWidget(self.resetBtn, 0, 2, 1, 1)
        self.ceaseBtn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ceaseBtn.setFont(font)
        self.ceaseBtn.setObjectName("ceaseBtn")
        self.gridLayout_3.addWidget(self.ceaseBtn, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.communication_status = QtWidgets.QTextBrowser(self.groupBox_6)
        self.communication_status.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.communication_status.setFont(font)
        self.communication_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.communication_status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.communication_status.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.communication_status.setTabStopWidth(40)
        self.communication_status.setObjectName("communication_status")
        self.horizontalLayout_4.addWidget(self.communication_status)
        self.gridLayout_4.addWidget(self.groupBox_6, 7, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testingStatus = QtWidgets.QLineEdit(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.testingStatus.setFont(font)
        self.testingStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.testingStatus.setReadOnly(True)
        self.testingStatus.setObjectName("testingStatus")
        self.horizontalLayout.addWidget(self.testingStatus)
        self.gridLayout_4.addWidget(self.groupBox_7, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "测试数据"))
        item = self.testing_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "测试产品"))
        item = self.testing_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "步骤"))
        item = self.testing_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "测试描述"))
        item = self.testing_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "测试类型"))
        item = self.testing_data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "测试电压"))
        item = self.testing_data.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "测试时间"))
        item = self.testing_data.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "测试电流"))
        item = self.testing_data.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "测试步骤数"))
        item = self.testing_data.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "测试状态"))
        self.groupBox.setTitle(_translate("MainWindow", "基本信息"))
        self.label.setText(_translate("MainWindow", "部件号："))
        self.label_7.setText(_translate("MainWindow", "订单号："))
        self.label_12.setText(_translate("MainWindow", "已测数量："))
        self.label_15.setText(_translate("MainWindow", "测试用时间："))
        self.label_5.setText(_translate("MainWindow", "型号："))
        self.label_8.setText(_translate("MainWindow", "订单测试数量："))
        self.label_13.setText(_translate("MainWindow", "合格数量："))
        self.label_16.setText(_translate("MainWindow", "ID号："))
        self.label_6.setText(_translate("MainWindow", "SAP No.："))
        self.label_9.setText(_translate("MainWindow", "操作员："))
        self.label_14.setText(_translate("MainWindow", "失败数量："))
        self.label_17.setText(_translate("MainWindow", "当前时间："))
        self.groupBox_5.setTitle(_translate("MainWindow", "测试列状态"))
        self.groupBox_2.setTitle(_translate("MainWindow", "测试提示"))
        self.groupBox_3.setTitle(_translate("MainWindow", "操作"))
        self.startBtn.setText(_translate("MainWindow", "开始"))
        self.resetBtn.setText(_translate("MainWindow", "停止"))
        self.ceaseBtn.setText(_translate("MainWindow", "退出"))
        self.groupBox_6.setTitle(_translate("MainWindow", "通讯状态"))
        self.communication_status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt; font-weight:96;\"><br /></p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "测试状态"))


